forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/concat', :latest
mod 'puppetlabs-puppet_agent', :latest
mod 'puppetlabs/ntp', :latest
mod 'puppetlabs/motd', :latest
mod 'puppetlabs-registry', :latest
mod 'puppetlabs-firewall', :latest
mod 'ghoneycutt-ssh', :latest
mod 'ghoneycutt-common', :latest
mod 'puppetlabs-accounts', :latest
mod 'saz-sudo', :latest
mod 'puppetlabs/apt', :latest
mod 'puppet-epel', '3.0.1'
mod 'puppet-unattended_upgrades', :latest
mod 'puppetlabs-docker',:latest